* Introduction
Training accurate and robust machine learning models requires high-quality data, but this is in short supply, restricting progress in both research and industry. The authors regret their inability to compel teams and laboratories to release their data, but know that by releasing this library we may at least democratize the production of new datasets.

The yawning dearth of publicly-available data for training denoising and other models is particularly apparent in the field of document analysis, where nearly all the data is either scans of medieval manuscripts or proprietary corporate information. Augraphy is designed to address this unmet need, by turning clean digital documents into realistically dirty versions, simulating normal wear and distortion that might occur during standard use as a printed document. Augraphy excels at reproducing effects like the dark regions that appear from old fax machines, the lighting gradient when the page doesn't make perfect contact with the scanner bed, or the tracks left on the page by dirty rollers and print drums.

By synthetically generating and adding noise, rather than introducing it naturally, we can keep clean ground truth documents alongside our noisy versions, making model training relatively straightforward. Beyond this, Augrapy provides complete control over the kind of effects generated by its pipelines, and allows datasets to be /declared/ rather than /invoked/, moving data acquisition and cleaning into the broader analysis pipeline rather than remaining a manual preprocessing step.
